name: Deploy ness

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - stage

on:
  push:
    branches:
      - ness/master-dy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Install dependencies
        run: pnpm install

      - name: Create environment file
        run: |
          echo "${{ secrets.STAGE_ENV }}" > web/ness/.env.stage

      - name: Build web projects
        run: |
          cd web/ness
          pnpm build

      - name: Prepare deployment package
        run: |
          # Create deployment directory structure

          mkdir -p ness/
          cp package.json ness/
          cp pnpm-lock.yaml ness/
          cp pnpm-workspace.yaml ness/
          cp -r web/ness/build ness/

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: plitvice-deployment
          path: plitvice/
          retention-days: 7

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Shut down servers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_SCRIPT_PATH }}
            ./shutdown.sh
            echo "Servers shut down successfully"
          EOF
          
      - name: Deploy to EC2
        run: |
          # Copy entire deployment package
          echo "Deploying plitvice package..."
          scp -o StrictHostKeyChecking=no -r plitvice/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_BUILD_PATH }}/
      
      - name: Restart servers via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_SCRIPT_PATH }}
            ./reboot.sh
            echo "Servers rebooted successfully"
          EOF
      